# Generated by Django 4.2.5 on 2023-12-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_days', models.CharField(max_length=100)),
                ('mass_date', models.DateField()),
                ('mass_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mass_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Details_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('organizer', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField()),
                ('cost', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/')),
                ('event_description', models.CharField(max_length=1000)),
                ('description_image', models.ImageField(upload_to='images/')),
                ('event_venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('event_gallery_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MinistriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_times', models.ImageField(upload_to='images/')),
                ('ask_for_prayer', models.ImageField(upload_to='images/')),
                ('obitury', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.ImageField(upload_to='')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_app.event_details_model')),
            ],
        ),
    ]
