# Generated by Django 4.2.5 on 2023-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_special_masses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obituary_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
