# Generated by Django 4.2.5 on 2023-12-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_obituary_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
