# Generated by Django 4.2.5 on 2023-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0005_blog_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details_model',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
