# Generated by Django 4.2.5 on 2023-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_alter_event_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details_model',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
