# Generated by Django 4.2.5 on 2023-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0009_alter_event_details_model_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_News_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
